[workspace]
members = [
  "node",
  "selectors",
  "c"
]

[package]
authors = ["Devon Govett <devongovett@gmail.com>"]
name = "parcel_css"
version = "1.0.0-alpha.31"
description = "A CSS parser, transformer, and minifier"
license = "MPL-2.0"
edition = "2021"
keywords = [ "CSS", "minifier", "Parcel" ]
repository = "https://github.com/parcel-bundler/parcel-css"

[[bin]]
name = "parcel_css"
path = "src/main.rs"
required-features = ["cli"]

[lib]
name = "parcel_css"
path = "src/lib.rs"
crate-type = ["rlib"]

[dependencies]
serde = { version = "1.0.123", features = ["derive"] }
cssparser = "0.29.1"
parcel_selectors = { version = "0.24.5", path = "./selectors" }
itertools = "0.10.1"
smallvec = { version = "1.7.0", features = ["union"] }
bitflags = "1.3.2"
parcel_sourcemap = { version = "2.1.0", features = ["json"] }
data-encoding = "2.3.2"
lazy_static = "1.4.0"
const-str = "0.3.1"
# CLI deps
clap = { version = "3.0.6", features = ["derive"], optional = true }
pathdiff = { version = "0.2.1", optional = true }
browserslist-rs = { version = "0.7.0", optional = true }
rayon = "1.5.1"
dashmap = "5.0.0"
serde_json = { version = "1.0.78", optional = true }

[target.'cfg(target_os = "macos")'.dependencies]
jemallocator = { version = "0.3.2", features = ["disable_initial_exec_tls"], optional = true }

[dev-dependencies]
indoc = "1.0.3"
assert_cmd = "2.0"
assert_fs = "1.0"
predicates = "2.1"
serde_json = "1"

[features]
default = ["grid"]
browserslist = ["browserslist-rs"]
cli = ["clap", "serde_json", "pathdiff", "browserslist", "jemallocator"]
grid = []
serde = ["smallvec/serde", "cssparser/serde"]

[[test]]
name = "cli_integration_tests"
path = "tests/cli_integration_tests.rs"
required-features = ["cli"]

[profile.release]
lto = true
codegen-units = 1
panic = 'abort'
